version: '3.8'

services:
  looking-glass:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - ./config:/root/config:ro
      - ./logs:/root/logs
    environment:
      - GIN_MODE=release
      - PORT=3002
    restart: unless-stopped
